# Generated by Django 6.1.1 on 2026-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculyator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinchi_son', models.FloatField()),
                ('amal', models.CharField(choices=[('+', "qo'shish+"), ('-', 'ayirish-'), ('*', "ko'paytirish"), ('/', "bo'lish")], max_length=1)),
                ('ikkinchi_son', models.FloatField()),
                ('natija', models.FloatField()),
            ],
        ),
    ]
