# Generated by Django 6.1.1 on 2026-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculyator',
            name='amal',
            field=models.CharField(choices=[('+', "qo'shish+"), ('-', 'ayirish-'), ('*', "ko'paytirish"), ('/', "bo'lish"), ('^', 'daraja'), ('sin', 'sinus'), ('cos', 'kosinus'), ('tan', 'tangens'), ('sqr', 'kvadrat'), ('sqrt', 'ildiz'), ('fact', 'faktorial')], max_length=10),
        ),
        migrations.AlterField(
            model_name='calculyator',
            name='ikkinchi_son',
            field=models.FloatField(default=0),
        ),
    ]
